FROM ghost:2.19.4-alpine

WORKDIR /var/lib/ghost

RUN mkdir -p ./content.orig/adapters/storage/s3 && \
  npm install ghost-storage-adapter-s3 && \
  cp -r ./node_modules/ghost-storage-adapter-s3/* ./content.orig/adapters/storage/s3

COPY ./config.json /var/lib/ghost/config.production.json